on:
  pull_request:
    types:
      - opened

jobs:
  post_comment:
    runs-on: ubuntu-latest
    steps:
      - env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          gh pr comment $PR_NUMBER --body "REVIEWS!"
